server:
  port: 8080

jwt:
  issuer: cinema-backend

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/api/v1/auth/**
            - id: hall-service
              uri: lb://hall-service
              predicates:
                - Path=/api/v1/halls/**, /api/v1/seats/**, /api/v1/seat-types/**
            - id: movie-service
              uri: lb://movie-service
              predicates:
                - Path=/api/v1/movies/**
            - id: session-service
              uri: lb://session-service
              predicates:
                - Path=/api/v1/sessions/**
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/v1/users/**

