server:
  port: 8080

spring:
  application:
    name: hall-service
  flyway:
    enabled: true
    locations: classpath:db/migration/hall
    default-schema: hall_service_schema
    schemas: hall_service_schema

