server:
  port: 8080

spring:
  application:
    name: user-service
  flyway:
    enabled: true
    locations: classpath:db/migration/user
    default-schema: user_service_schema
    schemas: user_service_schema