server:
  port: 8080

spring:
  application:
    name: movie-service
  flyway:
    enabled: true
    locations: classpath:db/migration/movies
    default-schema: movie_service_schema
    schemas: movie_service_schema
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      file-size-threshold: 3MB
      resolve-lazily: false

tmdb:
  apiKey: eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI0OThlZjUyYzFhNDU2MzI0MzBmMDc4MmE5MDdmMGMyMCIsIm5iZiI6MTc1NzUyOTcyNi45OTIsInN1YiI6IjY4YzFjNjdlYWU2YzI4ODMwZTliZDY1YiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.m2-vvp7wlADpX_V4P8CJU_G62cggk_7Sj59bRHQFLgA