spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL}
  instance:
    prefer-ip-address: true

minio:
  config:
    endpoint: ${MINIO_ENDPOINT:http://minio:9000}
    external-endpoint: ${MINIO_EXTERNAL_ENDPOINT:http://localhost:9000}
    login: ${MINIO_LOGIN:minioadmin}
    password: ${MINIO_PASSWORD:minioadmin}
  buckets:
    posters:
      name: poster-storage
      url-expiration-hours: 24



